src/objects/ActionPlanTemplateTask__c.object
<CustomObject>
    <description>Action Plan Template Task detail</description>
    <fields>
        <fullName>ActionPlanTemplateTask__c</fullName>
        <label>Task Dependency</label>
        <referenceTo>ActionPlanTemplateTask__c</referenceTo>
        <relationshipLabel>APT Task Templates</relationshipLabel>
        <relationshipName>R00NR0000000VaVDMA0</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Action_Plan_Template__c</fullName>
        <label>Action Plan Template</label>
        <referenceTo>ActionPlanTemplate__c</referenceTo>
        <relationshipLabel>APT Task Templates</relationshipLabel>
        <relationshipName>apTasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>APT Task</label>
    <nameField>
        <label>APT Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>APT Task Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ActionPlanTemplateTasksSelector.cls
/**
 * This is a basic selector for APT for this app, note how it implements 
 **/
public class ActionPlanTemplateTasksSelector 
    extends fflib_SObjectSelector
    implements IActionPlanTemplateTasksSelector {
    
	public static IActionPlanTemplateTasksSelector newInstance()
	{
		return (IActionPlanTemplateTasksSelector) Application.Selector.newInstance(ActionPlanTemplateTask__c.SObjectType);
	}
	
	public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField> {
			ActionPlanTemplateTask__c.Id,
			ActionPlanTemplateTask__c.Action_Plan_Template__c
			
		};
	}

	public Schema.SObjectType getSObjectType()
	{
		return ActionPlanTemplateTask__c.sObjectType;
	}

	public List<ActionPlanTemplateTask__c> selectById(Set<ID> idSet)
	{
		return (List<ActionPlanTemplateTask__c>) selectSObjectsById(idSet);
	}

}