force-app/main/default/objects/ActionPlanTemplate__c/ActionPlanTemplate__c.object-meta.xml
<CustomObject>
    <description>Template for Action Plan</description>
    <label>Action Plan Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plan Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ActionPlanTemplate__c/fields/ImportId__c.field-meta.xml
<CustomField>
    <fullName>ImportId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>ImportId</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ActionPlanTemplate__c/fields/SkipDay__c.field-meta.xml
<CustomField>
    <fullName>SkipDay__c</fullName>
    <description>If a Due Date lands on a weekend it should be pushed to this day.</description>
    <label>Skip Day</label>
    <picklist>
        <picklistValues>
            <fullName>Friday</fullName>
        </picklistValues>
        <picklistValues>
            <fullName>Monday</fullName>
            <default>true</default>
        </picklistValues>
    </picklist>
    <type>Picklist</type>
</CustomField>

force-app/main/default/objects/ActionPlanTemplate__c/fields/SkipWeekends__c.field-meta.xml
<CustomField>
    <fullName>SkipWeekends__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If selected, tasks included in an Action Plan will not be given a Due Date that falls on a weekend.</description>
    <inlineHelpText>If selected, tasks included in an Action Plan will not be given a Due Date that falls on a weekend.</inlineHelpText>
    <label>Skip Weekends</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ActionPlanTemplate__c/fields/TaskRecordTypeID__c.field-meta.xml
<CustomField>
    <fullName>TaskRecordTypeID__c</fullName>
    <label>Task Record Type ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ActionPlanTemplatesSelector.cls
/**
 * This is a basic selector for APT for this app, note how it implements 
 **/
public class ActionPlanTemplatesSelector extends fflib_SObjectSelector
    implements IActionPlanTemplatesSelector {
    
	public static IActionPlanTemplatesSelector newInstance()
	{
		return (IActionPlanTemplatesSelector) Application.Selector.newInstance(ActionPlanTemplate__c.SObjectType);
	}
	
	public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField> {
			ActionPlanTemplate__c.Id,
			ActionPlanTemplate__c.Description__c,
			ActionPlanTemplate__c.Name,
			ActionPlanTemplate__c.ImportId__c,
			ActionPlanTemplate__c.SkipDay__c,
			ActionPlanTemplate__c.SkipDefaultCompanyHolidays__c,
			ActionPlanTemplate__c.SkipWeekends__c,
			ActionPlanTemplate__c.TaskRecordTypeID__c
		};
	}

	public Schema.SObjectType getSObjectType()
	{
		return ActionPlanTemplate__c.sObjectType;
	}

	public List<ActionPlanTemplate__c> selectById(Set<ID> idSet)
	{
		return (List<ActionPlanTemplate__c>) selectSObjectsById(idSet);
	}

	public List<ActionPlanTemplate__c> selectByIdWithTasks(Set<ID> idSet)
	{
		fflib_QueryFactory actionPlanTemplatesQueryFactory = newQueryFactory();

		//add the related tasks
		fflib_QueryFactory actionPlanTemplateTasksQueryFactory = 
			new ActionPlanTemplateTasksSelector()
			.addQueryFactorySubselect(ActionPlanTemplatesQueryFactory);
		
		return (List<ActionPlanTemplate__c>) Database.query(
			actionPlanTemplatesQueryFactory.toSOQL()
		);

	}

	public List<ActionPlanTemplate__c> selectAll() {
		return (List<ActionPlanTemplate__c>) Database.query (
			newQueryFactory()
				.setLimit(1000)
				.addOrdering('Name', fflib_QueryFactory.SortOrder.ASCENDING )
				.toSOQL()
			);
	}

}