force-app/main/default/objects/ActionPlanTemplate__c/ActionPlanTemplate__c.object-meta.xml
<CustomObject>
    <description>Template for Action Plan</description>
    <label>Action Plan Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plan Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ActionPlanTemplateTask__c.object
<CustomObject>
    <description>Action Plan Template Task detail</description>
    <fields>
        <fullName>ActionPlanTemplateTask__c</fullName>
        <label>Task Dependency</label>
        <referenceTo>ActionPlanTemplateTask__c</referenceTo>
        <relationshipLabel>APT Task Templates</relationshipLabel>
        <relationshipName>R00NR0000000VaVDMA0</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Action_Plan_Template__c</fullName>
        <label>Action Plan Template</label>
        <referenceTo>ActionPlanTemplate__c</referenceTo>
        <relationshipLabel>APT Task Templates</relationshipLabel>
        <relationshipName>apTasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>APT Task</label>
    <nameField>
        <label>APT Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>APT Task Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ActionPlanTemplateTask__c/fields/TemplateTaskDependency__c.field-meta.xml
<CustomField>
    <fullName>TemplateTaskDependency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Dependency</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Dependent Task required to be from same Action Plan Template</errorMessage>
        <filterItems>
            <field>$Source.Action_Plan_Template__c</field>
            <operation>equals</operation>
            <valueField>$Source.Action_Plan_Template__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ActionPlanTemplateTask__c</referenceTo>
    <relationshipLabel>Action Plan Template Tasks</relationshipLabel>
    <relationshipName>ActionPlanTemplateTasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ActionPlanTemplatesService.cls
public with sharing class ActionPlanTemplatesService {

 	
    public ActionPlanTemplatesDomain	actionPlanTemplates		{ get; set; }
    

    public ActionPlanTemplatesService() {

    }

    public static void saveAPT(Set<ID> aptIds){


    }

    public static ActionPlanTemplate__c getAPT(ID aptId){
        set<id> ids = new set<id>();
        ids.add(aptId);
        return ActionPlanTemplatesSelector.newInstance().selectByIdWithTasks(ids)[0];

    }


    public integer getTemplateTaskSize(){
        ActionPlanTemplate__c apt = (ActionPlanTemplate__c) actionPlanTemplates.records[0];
        
        integer x;
        if (apt.ActionPlanTemplateTasks__r.isEmpty()) {x = 0;}
        else {x = apt.ActionPlanTemplateTasks__r.size();}
            
       return x;
    }

    public string ErrorMsg(){
        return actionPlanTemplates.errorMsg;
    }

}